minimum_pre_commit_version: "2.13"
fail_fast: true
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, 'E722', --ignore, 'E501']
  - repo: git@github.com:sirwart/ripsecrets.git
    rev: v0.1.3
    hooks:
      - id: ripsecrets
