teamalias = {
    "Bucks": ["mil", "sucks"],
    "Bulls": ["chi"],
    "Cavaliers": ["cle", "cavs"],
    "Celtics": ["bos", "Cs", "C's", "selltix"],
    "Clippers": ["lac", "clips", "clipjoint"],
    "Grizzlies": ["mem", "grizz"],
    "Hawks": ["atl", "hotlanta"],
    "Heat": ["mia"],
    "Hornets": ["cha", "whorenets"],
    "Jazz": ["uta", "jizz", "spazz", "azz"],
    "Kings": ["sac"],
    "Knicks": ["nyk", "nix"],
    "Lakers": ["lal", "fakers", "lakeshow", "showtime"],
    "Magic": ["orl", "tragic"],
    "Mavericks": ["dal", "mavs", "fuck luka"],
    "Nets": ["bkn", "njn"],
    "Nuggets": ["den", "nugs"],
    "Pacers": ["ind"],
    "Pelicans": ["nop", "pels", "nollins"],
    "Pistons": ["det", "pissedons", "pissed ons"],
    "Raptors": ["tor", "craptors"],
    "Rockets": ["hou"],
    "Spurs": ["sas"],
    "Suns": ["phx"],
    "Timberwolves": ["min", "minny", "wolves"],
    "Thunder": ["okc", "blunder"],
    "Trail Blazers": ["por", "pdx", "trailblazers"],
    "Warriors": ["gsw", "dubs"],
    "Wizards": ["was", "wiz"],
}

confs = {
    "east": ["Atlantic", "Central", "Southeast"],
    "west": ["Southwest", "Northwest", "Pacific"],
    "eastern": ["Atlantic", "Central", "Southeast"],
    "western": ["Southwest", "Northwest", "Pacific"],
}

statnicks = {
    "GP": ["games played", "gms", "games", "played"],
    "MIN": ["minutes played", "mins", "minutes", "minplayed", "minsplayed"],
    "FGM": ["field goals", "field goals made"],
    "FGA": ["field goals attempted", "attempts", "shots taken", "shots attempted"],
    "FG_PCT": ["field goal %", "fg%", "shooting%"],
    "FG3M": ["3-pointers made", "3pm", "3s", "3's", "threes"],
    "FG3A": ["3-point attempts", "3pa", "chucks"],
    "FG3_PCT": ["3p%", "three point %", "3pt%"],
    "FTM": ["free throws made", "fts"],
    "FTA": ["free throw attempts"],
    "FT_PCT": ["free throw %", "ft%"],
    "OREB": ["offensive rebounds", "offensive boards"],
    "DREB": ["defensive rebounds", "defensive boards"],
    "REB": ["rebounds", "total rebounds", "boards", "glass"],
    "AST": ["assists", "dimes", "ass"],
    "STL": ["steals"],
    "BLK": ["blocks", "blocked shots", "rejections"],
    "TOV": ["turnovers", "giveaways"],
    "PF": ["fouls", "personal fouls"],
    "PTS": ["points", "ppg", "points per game"],
    "EFF": ["efficiency"],
    "ASS_TOV": ["ass:tov", "assists:turnovers", "atr", "a:t"],
    "STL_TOV": ["stl:tov", "steals:turnovers", "str", "s:t"],
}
