teamalias = {
    "Bucks": ["mil", "sucks"],
    "Bulls": ["chi"],
    "Cavaliers": ["cle", "cavs"],
    "Celtics": ["bos", "Cs", "C's", "selltix"],
    "Clippers": ["lac", "clips", "clipjoint"],
    "Grizzlies": ["mem", "grizz"],
    "Hawks": ["atl", "hotlanta"],
    "Heat": ["mia"],
    "Hornets": ["cha", "whorenets"],
    "Jazz": ["uta", "jizz", "spazz", "azz"],
    "Kings": ["sac"],
    "Knicks": ["nyk", "nix"],
    "Lakers": ["lal", "fakers", "lakeshow", "showtime"],
    "Magic": ["orl", "tragic"],
    "Mavericks": ["dal", "mavs", "fuck luka"],
    "Nets": ["bkn", "njn"],
    "Nuggets": ["den", "nugs"],
    "Pacers": ["ind"],
    "Pelicans": ["nop", "pels", "nollins"],
    "Pistons": ["det", "pissedons", "pissed ons"],
    "Raptors": ["tor", "craptors"],
    "Rockets": ["hou"],
    "Spurs": ["sas"],
    "Suns": ["phx"],
    "Timberwolves": ["min", "minny", "wolves"],
    "Thunder": ["okc", "blunder"],
    "Trail Blazers": ["por", "pdx", "trailblazers"],
    "Warriors": ["gsw", "dubs"],
    "Wizards": ["was", "wiz"],
}
